#!/usr/bin/env python3
"""Resolve conflicted .po catalogs entry by entry, using the documented three cases.

Catalog conflicts are the slowest part of every upstream merge: 34 locales, and this
fork carries 318 msgids upstream does not have, so the files can never be identical and
they conflict on almost every upstream string change. Resolving them by hand has been
corrected twice because the rule "which side wins" is not uniform.

It does a genuine three-way merge per entry, using the stages git already has during a
conflict, rather than parsing conflict markers:

    :1:path  base (merge base)    :2:path  ours    :3:path  theirs

Per entry, keyed on (msgctxt, msgid):

  only in ours                      keep ours     a fork-only string
  only in theirs                    take theirs   a new upstream string, with its
                                                  translation - taking "ours" here is
                                                  drift, and once produced 9 missing
                                                  translations per locale
  ours changed, theirs didn't       keep ours     the fork's own divergence
  theirs changed, ours didn't       take theirs   upstream updated a translation
  both changed, now differ          CONFLICT      fail closed; never guess
  both changed, now identical       take either

It FAILS CLOSED. If any entry is a genuine both-sides conflict the file is left alone
and reported, because a resolver that guesses is worse than resolving by hand.

Source references (#:) are regenerated by the project's i18n flow, so they are not
merged; run the extract afterwards as the documented procedure says.

Usage, from the repo root mid-merge:
    tools/upstream/resolve_po.py                 # report what it would do
    APPLY=1 tools/upstream/resolve_po.py         # write resolutions and git add them
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

APPLY = os.environ.get("APPLY") == "1"
PREFER_THEIRS = os.environ.get("PREFER_THEIRS") == "1"


def git(*a: str, binary: bool = False):
    r = subprocess.run(["git", *a], capture_output=True, check=False)
    if r.returncode != 0:
        return None
    return r.stdout if binary else r.stdout.decode("utf-8", "replace")


class Entry:
    __slots__ = ("comments", "ctxt", "msgid", "body", "obsolete")

    def __init__(self) -> None:
        self.comments: list[str] = []
        self.ctxt: str | None = None
        self.msgid: str | None = None
        self.body: list[str] = []  # msgstr / msgid_plural / msgstr[n] lines, verbatim
        self.obsolete = False

    def key(self):
        return (self.ctxt, self.msgid)

    def text(self) -> str:
        return "\n".join([*self.comments, *self._head(), *self.body])

    def _head(self) -> list[str]:
        out = []
        if self.ctxt is not None:
            out.append(f'msgctxt "{self.ctxt}"')
        out.append(f'msgid "{self.msgid}"' if self.msgid is not None else 'msgid ""')
        return out

    def translation(self) -> str:
        """Just the translated payload, for comparison. Ignores comments and refs."""
        return "\n".join(line for line in self.body if not line.startswith("#"))


STR_RE = re.compile(r'"((?:[^"\\]|\\.)*)"')


def _joined(lines: list[str]) -> str:
    return "".join("".join(STR_RE.findall(ln)) for ln in lines)


def parse(text: str) -> tuple[list[str], dict[tuple, Entry], int]:
    """Return (header_lines, entries_by_key, parsed_count)."""
    header: list[str] = []
    entries: dict[tuple, Entry] = {}
    blocks = re.split(r"\n\s*\n", text.strip("\n"))
    count = 0
    for i, block in enumerate(blocks):
        lines = [ln for ln in block.split("\n") if ln.strip()]
        if not lines:
            continue
        # the first block whose msgid is empty is the PO header
        ids = [ln for ln in lines if ln.startswith("msgid ")]
        if i == 0 and ids and _joined([ids[0]]) == "":
            header = lines
            continue
        # Obsolete blocks (#~ msgid ...) carry their directives behind a comment marker,
        # so the comment branch below would swallow the msgid and every such block would
        # key on (None, "") - colliding and silently overwriting one another. They are
        # commented-out history; the extract regenerates them. Skip the block entirely.
        if all(ln.startswith("#") for ln in lines) or any(
            ln.startswith("#~") for ln in lines
        ):
            continue
        e = Entry()
        mode = None
        idl: list[str] = []
        ctxl: list[str] = []
        for ln in lines:
            if ln.startswith("#"):
                (e.comments if mode is None else e.body).append(ln)
                continue
            if ln.startswith("msgctxt "):
                mode = "ctxt"; ctxl = [ln]; continue
            if ln.startswith("msgid "):
                mode = "id"; idl = [ln]; continue
            if ln.startswith(("msgstr", "msgid_plural")):
                mode = "body"; e.body.append(ln); continue
            if ln.startswith('"'):
                {"ctxt": ctxl, "id": idl, "body": e.body}[mode or "body"].append(ln)
                continue
            e.body.append(ln)
        e.msgid = _joined(idl)
        e.ctxt = _joined(ctxl) if ctxl else None
        entries[e.key()] = e
        count += 1
    return header, entries, count


def resolve(path: str) -> tuple[str, dict]:
    base_t = git("show", f":1:{path}")
    ours_t = git("show", f":2:{path}")
    theirs_t = git("show", f":3:{path}")
    if ours_t is None or theirs_t is None:
        return "skip", {"why": "not a three-stage conflict"}

    _, base, nb = parse(base_t or "")
    ohdr, ours, no = parse(ours_t)
    thdr, theirs, nt = parse(theirs_t)
    if min(no, nt) < 10:
        return "error", {"why": f"parsed implausibly few entries (ours {no}, theirs {nt})"}

    stats = dict(base=nb, ours=no, theirs=nt, keep_ours=0, take_theirs=0,
                 ours_only=0, theirs_only=0, same=0, conflict=0)
    conflicts: list[str] = []
    out: list[Entry] = []

    for key in list(ours.keys()) + [k for k in theirs if k not in ours]:
        o, t, b = ours.get(key), theirs.get(key), base.get(key)
        if o is not None and t is None:
            # upstream does not have it: a fork-only string, or upstream deleted it.
            # Keeping ours is right for the first, and safe for the second ONLY because
            # the extract afterwards drops entries no source string references. Note the
            # deeper trap, which bites any format without an extract step: the merge base
            # is an UPSTREAM commit, so a fork-branded value differs from base BY
            # CONSTRUCTION. Key existence and value wording are therefore separate
            # questions, and conflating them keeps fork-branded entries whose upstream key
            # is deliberately gone.
            out.append(o); stats["ours_only"] += 1; continue
        if o is None and t is not None:
            out.append(t); stats["theirs_only"] += 1; continue
        assert o is not None and t is not None
        ot, tt = o.translation(), t.translation()
        if ot == tt:
            out.append(o); stats["same"] += 1; continue
        bt = b.translation() if b is not None else None
        if bt is not None and ot == bt:
            out.append(t); stats["take_theirs"] += 1; continue
        if bt is not None and tt == bt:
            out.append(o); stats["keep_ours"] += 1; continue
        if PREFER_THEIRS and "Fluxer" not in tt:
            # Opt-in for a deliberate adoption of upstream's feature (ADR 0012): both
            # sides translated the same new string. Upstream wins, except where its text
            # carries the upstream brand, which stays a hand decision.
            out.append(t); stats["take_theirs"] += 1; continue
        stats["conflict"] += 1
        conflicts.append(f'{key[1][:70]!r}')
        out.append(o)

    if stats["conflict"]:
        return "conflict", {**stats, "entries": conflicts[:8]}

    # The header is generated and ours normally differs from theirs only in stamp
    # fields, so theirs is taken. That was measured true for all 34 catalogs, but it is
    # an assumption, so assert it rather than trust it: if ours carries anything beyond
    # the known stamps, block the file instead of discarding a fork header field.
    STAMPS = (
        "PO-Revision-Date", "POT-Creation-Date", "Last-Translator",
        "X-Generator", "Language-Team", "Report-Msgid-Bugs-To",
    )
    def significant(lines: list[str]) -> list[str]:
        keep = []
        for ln in lines:
            if ln.startswith("#") or ln.strip() in ('msgid ""', 'msgstr ""'):
                continue
            if any(f'"{k}:' in ln for k in STAMPS):
                continue
            keep.append(ln.strip())
        return sorted(keep)

    if significant(ohdr) != significant(thdr):
        only_ours = [x for x in significant(ohdr) if x not in significant(thdr)]
        return "conflict", {
            **stats,
            "conflict": 1,
            "entries": [f"header differs beyond stamps: {only_ours[:2]}"],
        }

    body = "\n\n".join([("\n".join(thdr or ohdr))] + [e.text() for e in out])
    return "resolved", {**stats, "text": body + "\n"}


def main() -> int:
    root = git("rev-parse", "--show-toplevel")
    if not root:
        print("not a git repo", file=sys.stderr); return 2
    os.chdir(root.strip())
    if git("rev-parse", "--verify", "-q", "MERGE_HEAD") is None:
        print("no merge in progress: nothing to resolve", file=sys.stderr); return 1

    unmerged = [
        ln.split("\t")[-1]
        for ln in (git("diff", "--name-only", "--diff-filter=U") or "").splitlines()
        if ln.endswith(".po")
    ]
    if not unmerged:
        print("no conflicted .po files"); return 0

    print(f"conflicted catalogs: {len(unmerged)}   mode: {'APPLY' if APPLY else 'REPORT'}")
    totals = dict(resolved=0, conflict=0, skip=0, error=0)
    blocked: list[str] = []
    for path in unmerged:
        verdict, info = resolve(path)
        totals[verdict] = totals.get(verdict, 0) + 1
        loc = path.split("/")[-2] if "/" in path else path
        if verdict == "resolved":
            s = info
            print(f"  {loc:<8} ours_only={s['ours_only']:<4} theirs_only={s['theirs_only']:<4} "
                  f"keep_ours={s['keep_ours']:<3} take_theirs={s['take_theirs']:<3} same={s['same']}")
            if APPLY:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(info["text"])
                git("add", path)
        elif verdict == "conflict":
            blocked.append(path)
            print(f"  {loc:<8} BLOCKED: {info['conflict']} entries changed on both sides")
            for e in info["entries"]:
                print(f"             {e}")
        else:
            print(f"  {loc:<8} {verdict}: {info.get('why')}")

    print()
    print(f"resolved {totals['resolved']}, blocked {totals['conflict']}, "
          f"skipped {totals['skip']}, errors {totals['error']}")
    if blocked:
        print("\nBlocked files are left untouched and still conflicted. Resolve those by")
        print("hand: both sides changed the same translation, and guessing is how the")
        print("documented rule got this wrong twice.")
    if APPLY and totals["resolved"]:
        print("\nNow regenerate source references through the project's own flow:")
        print("  pnpm --filter fluxer_app i18n:extract   (then i18n:compile)")
    return 1 if (blocked or totals["error"]) else 0


if __name__ == "__main__":
    sys.exit(main())
